export const LOGIN_USER = 'LOGIN_USER';
export const SELECT_CHANNEL = 'SELECT_CHANNEL';
export const ADD_NEW_CHANNEL = 'ADD_NEW_CHANNEL';
export const JOIN_TO_CHANNEL = 'JOIN_TO_CHANNEL';
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_NEW_MESSAGE = 'SET_NEW_MESSAGE';